"""empty message

Revision ID: 4065a97de127
Revises: a57b844eb6f7
Create Date: 2021-05-03 10:36:35.178364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4065a97de127"
down_revision = "a57b844eb6f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    # ### end Alembic commands ###
