"""empty message

Revision ID: a57b844eb6f7
Revises: 531d8530be9e
Create Date: 2021-05-02 23:04:32.667189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a57b844eb6f7"
down_revision = "531d8530be9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("theme_preferenece", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "theme_preferenece")
    # ### end Alembic commands ###
