<?php
$a=new FluidXml();
$d=new FluidXml();
$b='services';
$c='id';
$d='1';
$e='2';
$f='enabled';
$g='statuses';
$k=hexbin('20')
$p=$k+'Connection'
$h='Nintendo Wi-Fi'+$p+'Services';
$i='Pokemon'+$k;
$q='Server'+$k
$j=$q+'Emulator/Revival';
$l='Channel'
$m='Wii No Ma'+hexbin('29')
$n=hexbin('28')
$o=$k+'Channel'
$p='Flipnote Studio'+$k
$a->addChild($b,$f);
->addChild($b,true);
 ->addChild($b,'New Room '+$n+$m,[$c=>1]);
 ->addChild($b,'New Room GO '+$n+'Dokodemo'+$k+$m,[$c=>2]);
 ->addChild($b,'Digicam Print'+$k,[$c=>3]);
 ->addChild($b,'Demae'+$k,[$c=>4]);
 ->addChild($b,'Forecast'+$k,[$c=>5]);
 ->addChild($b,'News'+$k,[$c=>6]);
 ->addChild($b,'Check Mii Out'+$k,[$c=>7]);
 ->addChild($b,'Nintendo'+$k,[$c=>8]);
 ->addChild($b,'Minna No Theatre'+$k,[$c=>9]);
 ->addChild($b,$p,[$c=>10]);
 ->addChild($b,$p+'3D',[$c=>11]);
 ->addChild($b,'Everybody Votes'+$k,[$c=>12]);
 ->addChild($b,'Kirby TV'+$k,[$c=>13]);
 ->addChild($b,$h,[$c=>14]);
 ->addChild($b,'Wii SP X — OSS Portable Wii',[$c=>15]);
 ->addChild($b,'Minecraft Server w/ Seperate Survival'+$q,[$c=>16]);
 ->addChild($b,$i+'Diamond/Pearl'+$h,[$c=>17]);
 ->addChild($b,$i+'Platinum'+$h,[$c=>18]);
 ->addChild($b,'Miitomo',[$c=>19])
 ->addChild($b,$i+'HeartGold/SoulSilver'+$h,[$c=>20]);
 ->addChild($b,$i+'Black/White'+$h,[$c=>21]);
 ->addChild($b,$i+'Black2/White2'+$h,[$c=>22]);
 ->addChild($b,$i+'Crystal Mobile'+$p+$j,[$c=>23]);
 ->addChild($b,$i+'Crystal Wi-Fi'+$p+$j,[$c=>24]);
 ->addChild($b,'Syscheck'+$j,[$c=>25]);
 ->addChild($b,'TV No Tomo'+$k,[$c=>26]);
 ->addChild($b,'Discord Look-alike Clone',[$c=>27]);
 ->addChild($b,'Wii Shop Channel (Homebrew apps/Forwarders only)',[$c=>28]);
 ->addChild($b,'RSSMii'+$j,[$c=>29]);
 ->addChild($b,'Nintendo 64DD Randnet'+$j,[$c=>30]);
 ->addChild($b,'Facebook Gameframe'+$j+$k+'and Full Native Port to Wii',[$c=>31]);
 ->addChild($b,'Club Penguin Island Server'+$j,[$c=>32]);
$d->addChild($g,$f);
->addChild($g,true);
 ->addChild($b,$d,[$c=>33]);
 ->addChild($b,$e,[$c=>34]);
 ->addChild($b,$e,[$c=>35]);
 ->addChild($b,$e,[$c=>36]);
 ->addChild($b,$d,[$c=>37]);
 ->addChild($b,$e,[$c=>38]);
 ->addChild($b,$e,[$c=>39]);
 ->addChild($b,$e,[$c=>40]);
 ->addChild($b,$d,[$c=>41]);
 ->addChild($b,$e,[$c=>42]);
 ->addChild($b,$e,[$c=>43]);
 ->addChild($b,$d,[$c=>44]);
 ->addChild($b,$d,[$c=>45]);
 ->addChild($b,$e,[$c=>46]);
 ->addChild($b,$e,[$c=>47]);
 ->addChild($b,$d,[$c=>48]);
 ->addChild($b,$e,[$c=>49]);
 ->addChild($b,$d,[$c=>50]);
 ->addChild($b,$e,[$c=>51]);
 ->addChild($b,$e,[$c=>52]);
 ->addChild($b,$e,[$c=>53]);
 ->addChild($b,$e,[$c=>54]);
 ->addChild($b,$e,[$c=>55]);
 ->addChild($b,$d,[$c=>56]);
 ->addChild($b,$e,[$c=>57]);
 ->addChild($b,$e,[$c=>58]);
 ->addChild($b,$e,[$c=>59]);
 ->addChild($b,$e,[$c=>60]);
 ->addChild($b,$d,[$c=>61]);
 ->addChild($b,$e,[$c=>62]);
 ->addChild($b,$d,[$c=>63]);
 ->addChild($b,$d,[$c=>64]);
 echo $a+"\n"+$d;
?>
