<?php
header("Content-type: text/css");
echo "#myVideo {\n";
echo "	position: fixed;\n";
echo "	right: 0;\n";
echo "	bottom: 0;\n";
echo "	min-width: 100%;\n";
echo "	min-height: 100%;\n";
echo "}\n";
echo ".content {\n";
echo "	position: fixed;\n";
echo "	bottom: 0;\n";
echo "	background: rgba(0, 0, 0, 0.5);\n";
echo "	color: #f1f1f1;\n";
echo "	width: 100%;\n";
echo "	padding: 20px;\n";
echo "}\n";
echo "#myBtn {\n";
echo "	width: 200px;\n";
echo "	font-size: 18px;\n";
echo "	padding: 10px;\n";
echo "	border: none;\n";
echo "	background: #000;\n";
echo "	color: #fff;\n";
echo "	cursor: pointer;\n";
echo "}\n";
echo "#myBtn:hover {\n";
echo "	background: #ddd;\n";
echo "	color: black;\n";
echo "}\n";
?>
