#!/bin/bash
#Argument reference: https://stackoverflow.com/questions/3975004/how-to-make-a-multi-character-parameter-in-unix-using-getopt
function show_help {
    echo "usage:  $BASH_SOURCE --output <directory you want to output to> --mode <mode you want nidotool to initalize in>"
    echo "                     --output - directory you want to output to"
    echo "                     --mode - mode you want nidotool to initalize in"
}
ARGUMENT_LIST=(
    "output"
    "mode"
    "h"
)
opts=$(getopt \
    --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
    --name "$(basename "$0")" \
    --options "" \
    -- "$@"
)
echo $opts
eval set --$opts
while true; do
    case "$1" in
    --h)
        show_help
        exit 0
        ;;
    --output)  
        shift
        data=$1
        ;;
    --mode)  
        shift
        selector=$1
        ;;
      --)
        shift
        break
        ;;
    esac
    shift
done
if [[ $selector == 0 ]];then
 mkdir $data/"008"
elif [[ $selector == 1 ]];then
 mkdir $data/"009"
elif [[ $selector == 2 ]];then
 mkdir $data/"010"
elif [[ $selector == 3 ]];then
 mkdir $data/"011"
elif [[ $selector == 4 ]];then
 mkdir $data/"012"
elif [[ $selector == 5 ]];then
 mkdir $data/"013"
elif [[ $selector == 6 ]];then
 mkdir $data/"014"
elif [[ $selector == 7 ]];then
 mkdir $data/"015"
elif [[ $selector == 8 ]];then
 mkdir $data/"016"
elif [[ $selector == 9 ]];then
 mkdir $data/"017"
elif [[ $selector == 10 ]];then
 mkdir $data/"018"
elif [[ $selector == 11 ]];then
 mkdir $data/"019"
elif [[ $selector == 12 ]];then
 mkdir $data/"020"
elif [[ $selector == 13 ]];then
 mkdir $data/"021"
elif [[ $selector == 14 ]];then
 mkdir $data/"022"
elif [[ $selector == 15 ]];then
 mkdir $data/"023"
elif [[ $selector == 16 ]];then
 mkdir $data/"024"
elif [[ $selector == 17 ]];then
 mkdir $data/"025"
elif [[ $selector == 18 ]];then
 mkdir $data/"026"
elif [[ $selector == 19 ]];then
 mkdir $data/"027"
elif [[ $selector == 20 ]];then
 mkdir $data/"028"
elif [[ $selector == 21 ]];then
 mkdir $data/"029"
elif [[ $selector == 22 ]];then
 mkdir $data/"030"
elif [[ $selector == 23 ]];then
 mkdir $data/"031"
elif [[ $selector == 24 ]];then
 mkdir $data/"032"
elif [[ $selector == 25 ]];then
 mkdir $data/"033"
elif [[ $selector == 26 ]];then
 mkdir $data/"034"
elif [[ $selector == 27 ]];then
 mkdir $data/"035"
elif [[ $selector == 28 ]];then
 mkdir $data/"036"
elif [[ $selector == 29 ]];then
 mkdir $data/"037"
elif [[ $selector == 30 ]];then
 mkdir $data/"038"
elif [[ $selector == 31 ]];then
 mkdir $data/"039"
elif [[ $selector == 32 ]];then
 mkdir $data/"040"
elif [[ $selector == 33 ]];then
 mkdir $data/"041"
elif [[ $selector == 34 ]];then
 mkdir $data/"042"
elif [[ $selector == 35 ]];then
 mkdir $data/"043"
elif [[ $selector == 36 ]];then
 mkdir $data/"044"
elif [[ $selector == 37 ]];then
 mkdir $data/"045"
elif [[ $selector == 38 ]];then
 mkdir $data/"046"
elif [[ $selector == 39 ]];then
 mkdir $data/"047"
elif [[ $selector == 40 ]];then
 mkdir $data/"048"
elif [[ $selector == 41 ]];then
 mkdir $data/"049"
elif [[ $selector == 42 ]];then
 mkdir $data/"050"
elif [[ $selector == 43 ]];then
 mkdir $data/"051"
elif [[ $selector == 44 ]];then
 mkdir $data/"052"
elif [[ $selector == 45 ]];then
 mkdir $data/"065"
elif [[ $selector == 46 ]];then
 mkdir $data/"082"
elif [[ $selector == 47 ]];then
 mkdir $data/"095"
elif [[ $selector == 48 ]];then
 mkdir $data/"110"
elif [[ $selector == 49 ]];then
 ./datatool 0
elif [[ $selector == 50 ]];then
 ./datatool 1
elif [[ $selector == 51 ]];then 
 ./datatool 2
elif [[ $selector == 52 ]];then
 ./datatool 3
elif [[ $selector == 53 ]];then
 ./datatool 4
elif [[ $selector == 54 ]];then
 ./datatool 5
elif [[ $selector == 55 ]];then
 ./datatool 6
elif [[ $selector == 56 ]];then
 ./datatool 7
elif [[ $selector == 57 ]];then
 ./datatool 8
elif [[ $selector == 58 ]];then
 ./datatool 9
elif [[ $selector == 59 ]];then
 ./datatool 10
elif [[ $selector == 60 ]];then
 ./datatool 11
elif [[ $selector == 61 ]];then
 ./datatool 12
elif [[ $selector == 62 ]];then
 ./datatool 13
elif [[ $selector == 63 ]];then
 ./datatool 14
elif [[ $selector == 64 ]];then
 ./datatool 15
elif [[ $selector == 65 ]];then
 ./datatool 16
elif [[ $selector == 66 ]];then
 ./datatool 17
elif [[ $selector == 67 ]];then
 ./datatool 18
elif [[ $selector == 68 ]];then
 ./datatool 19
elif [[ $selector == 69 ]];then
 ./datatool 20
elif [[ $selector == 70 ]];then
 ./datatool 21
elif [[ $selector == 71 ]];then
 ./datatool 22
elif [[ $selector == 72 ]];then
 ./datatool 23
elif [[ $selector == 73 ]];then
 ./datatool 24
elif [[ $selector == 74 ]];then
 ./datatool 25
elif [[ $selector == 75 ]];then
 ./datatool 26
elif [[ $selector == 76 ]];then
 ./datatool 27
elif [[ $selector == 77 ]];then
 ./datatool 28
elif [[ $selector == 78 ]];then
 ./datatool 29
elif [[ $selector == 79 ]];then
 ./datatool 30
elif [[ $selector == 80 ]];then
 ./datatool 31
elif [[ $selector == 81 ]];then
 ./datatool 32
elif [[ $selector == 82 ]];then
 ./datatool 33
elif [[ $selector == 83 ]];then
 ./datatool 34
elif [[ $selector == 84 ]];then
 ./datatool 35
elif [[ $selector == 85 ]];then
 ./datatool 36
elif [[ $selector == 86 ]];then
 ./datatool 37
elif [[ $selector == 87 ]];then
 ./datatool 38
elif [[ $selector == 88 ]];then
 ./datatool 39
elif [[ $selector == 89 ]];then
 ./datatool 40
elif [[ $selector == 90 ]];then
 ./datatool 41
elif [[ $selector == 91 ]];then
 ./datatool 42
elif [[ $selector == 92 ]];then
 ./datatool 43
elif [[ $selector == 93 ]];then
 ./datatool 44
elif [[ $selector == 94 ]];then
 ./datatool 45
elif [[ $selector == 95 ]];then
 ./datatool 46
elif [[ $selector == 96 ]];then
 ./datatool 47
elif [[ $selector == 97 ]];then
 ./datatool 48
elif [[ $selector == 98 ]];then
 ./datatool 49
elif [[ $selector == 99 ]];then
 ./datatool 50
else
 echo FATAL ERROR CODE 0 OCCURED
fi